spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/imc
    username: root
    password: Ct2010**
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
